# cache homepage for an hour
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "max-age=3600, public"

# aggressively cache everything else
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=604800, public"
